package token

type Type int

const (
	TOKEN_EOF Type = iota
	TOKEN_ILLEGAL
	TOKEN_SEISU
	TOKEN_RONRI
	TOKEN_RIPPOTAI
	TOKEN_HAIRETSU
	TOKEN_KANSU
	TOKEN_SHUKI
	TOKEN_SORENARA
	TOKEN_KIDO
	TOKEN_SHUSHI
	TOKEN_MODORU
	TOKEN_RUIKEI
	TOKEN_JIGEN
	TOKEN_SHINRI
	TOKEN_USO
	TOKEN_IDENTIFIER
	TOKEN_INTEGER
	TOKEN_HEX
	TOKEN_ASSIGN
	TOKEN_PLUS
	TOKEN_MINUS
	TOKEN_ASTERISK
	TOKEN_SLASH
	TOKEN_NOT
	TOKEN_LESS
	TOKEN_GREATER
	TOKEN_EQUALS
	TOKEN_NOTEQUALS
	TOKEN_AND
	TOKEN_OR
	TOKEN_ARROW
	TOKEN_PERCENT
	TOKEN_COMMA
	TOKEN_SEMICOLON
	TOKEN_COLON
	TOKEN_LPAREN
	TOKEN_RPAREN
	TOKEN_LBRACE
	TOKEN_RBRACE
	TOKEN_LBRACKET
	TOKEN_RBRACKET
	TOKEN_MOVE_UP
	TOKEN_MOVE_DOWN
	TOKEN_MOVE_LEFT
	TOKEN_MOVE_RIGHT
	TOKEN_MOVE_FORWARD
	TOKEN_MOVE_BACKWARD
	TOKEN_MEASURE_UP
	TOKEN_MEASURE_DOWN
	TOKEN_MEASURE_LEFT
	TOKEN_MEASURE_RIGHT
	TOKEN_MEASURE_FORWARD
	TOKEN_MEASURE_BACKWARD
	TOKEN_GET_POSITION
	TOKEN_BREAK_SEQUENCE
)
